name: gv

on:
  push:
    branches: [ main ]
    paths:
      - 'gv.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'gv.py'
  workflow_dispatch:
  schedule:
    - cron: '3 21 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GVURL: ${{ secrets.GVURL }}  # 全局变量
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: |
          rm secret.json
          mkdir -p results
          python gv.py

      - name: Commit changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update $(date +'%Y-%m-%d')" || echo "No changes"
          git push